### ISSUE TITLE
Error on iterators of strings.

### ISSUE THREAD

**Issue by gsilber** [boots-edu/textbook#28]
When using a string iterator (example for of), compiler reports string[] does not have an iterator.  This code works in typescript.

Example:
let fruits: string[] = ["apple","banana","orange"];
for (let fruit of fruits){
  console.log(fruit);
}
This also effects using the spread operator to populate function parameters, but I think it is the same issue.  View the arrays.md line 181 for an example of where this does not work as expected.

**Comment by acbart** [comment]
Oops, I accidentally had the wrong `d.ts` file loaded for the compiler. Fixed in d73351d!

**Comment by gsilber** [comment]
Can you take a look at datacass/constructor.md line 111.  This seems to run forever.

**Comment by acbart** [comment]
Moved to #29, but also basically fixed this (kind of). It's an issue with the system that checks the compiler information for the public/private keywords on class member variables. Since that system isn't really used for anything yet, I just disabled it for now. We can take a look at it later.

**Comment by gsilber** [comment]
It is currently working on all of my examples so far through chapter 5.
