### ISSUE TITLE
Issues with code running

### ISSUE THREAD

**Issue by gsilber** [boots-edu/textbook#31]
Here are some issues I have found with running code within the textbook environment.
* Testing features added: not,contains,instanceOf,toThrowError.  This is done.
* Include libraries like WebZ
* Include additional hidden code.
* Support for interfaces
* Support for declare statements

**Comment by gsilber** [comment]
reduce does not work properly as well (loops forever).

**Comment by acbart** [comment]
- **Testing**: Yeah, I only coded up the bare minimum functionality. I will investigate whether I should get Jest on here somehow (might not be hard now that I have better setup), or if I should re-implement them myself. There's a finite set.
- **Webz**: This is definitely mission critical. I think I have to loosen up some of the execution sandboxing to make it happen, but I wanted to experiment a little. Shouldn't be too hard though, and will be really cool to have.
- **Hidden code**: I agree, very useful feature. I'm thinking about using special comments to guard code, perhaps? Like `//---SKIP` or something. I'm not familiar with a particular convention here.
- **Interfaces**: Surprised that this doesn't work already. I must have configured something wrong.
- **Declare**: Again, surprised this doesn't work. I'll need to poke around.
- **Reduce**: I just tried a basic usage, and it worked. Can you give me the snippet that broke for you?

**Comment by gsilber** [comment]
So, reduce does work (sorry, I had a typo).

 

For interface, it works sometimes.  This code is problematic.

interface Point{

                x:number;

                y:number;

}

class DrawPoint implements Point{

                x:number;

                y:number;

                constructor(x:number, y:number, private color:string){

                                this.x=x;

                                this.y=y;

                }

}

const point:Point=new DrawPoint(4,5,"red");

 

For declare here is an example:

class Tiger{

                name:string="Tony";

                getDetails():string{

                                return this.name + " is a tiger";

                }

                eat(){

                                console.log("Yum");

                }

}


class Tree{

                name:string="Kevin";

                height:number=100;

                getDetails():string{

                                return this.name + " is " + this.height + " feet tall";

                }

}

declare type ThingsThatStartWithT=Tree|Tiger;

let whatisit:ThingsThatStartWithT;

 

Let me know.  I looked at your code and I think I could also fix some of this if you don’t have time.  

 

Greg

**Comment by gsilber** [comment]
Added support for toBeInstanceOf and toContain to tests

**Comment by gsilber** [comment]
Added support for not to tests.

**Comment by gsilber** [comment]
Instead of hidden code, perhaps it would be better to allow external imports.  This would solve both the WebZ and hidden code issues.  We could just package up the hidden code and inject it.  The webz library could then be packaged up and included in the same fashion.

**Comment by acbart** [comment]
#39 should handle the interfaces, enums, etc. Now we just need to get Webz working, if I follow this correctly. That will probably require removing the iframe code, but I'll investigate soon.

**Comment by gsilber** [comment]
Yes, this appears to work.  Thanks.  I will merge it in later (or you can).

 

Greg
