### ISSUE TITLE
Selective code runner

### ISSUE THREAD

**Issue by gsilber** [boots-edu/textbook#33]
It would be nice to have code highlighting without the run button.

Currently
```typescript

gives both.  Some code segments in the text are not runnable, but I would still like them highlighted as typescript.

**Comment by acbart** [comment]
I think this should be pretty easy to do with an Inline Attribute List that adds an additional class that deactivates the code runner! I'll take a stab sometime next week.

**Comment by gsilber** [comment]
I just submitted a pull request to fix this.  Since it is in your working code, I didn’t want to just merge it in like I have been doing with the text.  One line change to exclude the class no-run in setup_runners.ts.  If you are ok with it, please merge or send me a note to merge it myself.

 

Greg
