### ISSUE TITLE
New code causes hang on some code blocks

### ISSUE THREAD

**Issue by gsilber** [boots-edu/textbook#43]
Code in the following sections hangs:
Instances and References 
Class Methods
Data Hiding
Object Cloning

**Comment by acbart** [comment]
Ah, it looks like it is hanging on the imports, because I only set it up to import from the Webz library. I'll need to go add in the code to actually load our local imports too! I'll work on that today.

**Comment by gsilber** [comment]
Ohhh

 

I only did that because I could.  If it’s easier I can just move the code back into the window.  IT isn’t that much.

**Comment by acbart** [comment]
No need, I believe I have it now successfully importing and compiling those files. This did require adding the `export` keyword before the classes. It seems to be working from my experiments. It will also dump errors that are found in those files, with the filename.

**Comment by gsilber** [comment]
Awesome, I will let you know.

 

Thanks,
